include $(GOROOT)/src/Make.inc

TARG=mcobj
GOFILES=\
	alphaworld.go\
	betaworld.go\
	blocktypes.go\
	chunkmasks.go\
	enclosedChunk.go\
	mcobj.go\
	memorywriterpool.go\
	mtl.go\
	obj.go\
	prt.go\
	sideCache.go\
	sides.go\
	usage_$(GOOS).go\
	version.go\
	world.go\

include $(GOROOT)/src/Make.cmd
